# Disable Liquid processing for specific files
defaults:
  - scope:
      path: "tt_viz.html"
    values:
      render_with_liquid: false
  - scope:
      path: "**/*.html"
    values:
      render_with_liquid: false

# Exclude directories and files from Jekyll processing
exclude:
  - "daily/*/network"
  - "daily/*/network/coordination_network.html"
  - "**/coordination_network.html"
  - ".git"
  - ".github"
  - "**/.DS_Store"