# Disable Liquid processing for specific files
defaults:
  - scope:
      path: "tt_viz.html"
    values:
      render_with_liquid: false
  - scope:
      path: "**/*.html"
    values:
      render_with_liquid: false

# Exclude directories with network visualizations from Jekyll processing
exclude:
  - "daily/*/network"
  - "**/*_network.html"